services:
  postgres_db:
    image: postgres:16-alpine
    container_name: nest_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kanban_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres_db
  #   environment:
  #     DATABASE_HOST: postgres
  #     DATABASE_PORT: 5432
  #     DATABASE_USER: postgres
  #     DATABASE_PASSWORD: password
  #     DATABASE_NAME: kanban_db
  #     NODE_ENV: development

volumes:
  postgres_data:
